### PR TITLE
Added isAbstract and isInterface convenience ElementMatchers

### PR DESCRIPTION
**Pull request by CodingFabian**

### CODE REVIEW

**Comment by CodingFabian** [comment]
was created mostly using copy and paste, let me know if I missed a place where i should have copied and pasted as well :)

**Comment by raphw** [comment]
Thanks for that! Could you fix the trailing spaces and ammend the commit to your push? You can run alls tests locally with `-Pchecks -Pintegration`.

**Comment by CodingFabian** [comment]
didn't know about -Pchecks, thanks. Eclipse is pretty stubborn, do you happen to have an Eclipse formatter? Or only idea? :)

**Comment by raphw** [comment]
I use IntelliJ. The `checks` profile should be active by default.

**Pull request merged**
