### PR TITLE
Reduce memory allocation in CompoundList

### PR DESCRIPTION
**Pull request by testn**
CompoundList is often called with empty list.
This change will reduce the memory allocation 
in that case.

### CODE REVIEW

**Comment by raphw** [comment]
If the list is empty, it would probably be most efficient to return a singleton list returning the single element?

**Comment by testn** [comment]
Yes, it is. If possible, I actually want to refactor the entire library. It overuses ArrayList everywhere. If we make the library to use something similar to ImmutableList, it will make the optimization much easier.

**Comment by raphw** [comment]
Merged manually.

**Comment by PascalSchumacher** [comment]
I guess this should have 1.8.4 as milestone (as 1.8.3 was released on 31-Mar-2018)?

**Pull request closed without merging**
