### PR TITLE
 Fix IllegalArgumentException when dynamically subclassing classes from the default package in JDK9+

### LINKED ISSUE #568: Dynamic subclass of class from the default package causes IllegalArgumentException in JDK9+
This snippet of code:

```
        Class<?> type = new ByteBuddy()
                .subclass(NoPackageType.class)
                .make()
                .load(
                        NoPackageType.class.getClassLoader(),
                        MethodHandles.privateLookupIn(NoPackageType.class, MethodHandles.lookup())
                )
                .getLoaded();
```

causes this:

```
java.lang.IllegalArgumentException: NoPackageType$ByteBuddy$axU3ryhv must be defined in the same package as NoPackageType/package

	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1413)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:111)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:466)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5623)
	at net.bytebuddy.dynamic.scaffold.subclass.NoPackageSubclassDynamicTypeBuilderTest.testSubclassUsingLookup(NoPackageSubclassDynamicTypeBuilderTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

Will provide a PR with a test and hopefully a fix soon.

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #568

Not sure the tests are in the right package, and maybe there's a way to execute more tests on classes in the default package by extending some abstract base, but I don't know enough about the testing infrastructure to do better :)

### CODE REVIEW

**Comment by raphw** [comment]
Thanks, I did a few changes around the testing, I rather generate the class, but otherwise, great. Thanks for providing a fix!

**Comment by yrodiere** [comment]
Thanks! This bug affects Hibernate ORM ([HHH-13112](https://hibernate.atlassian.net/browse/HHH-13112)) and, through it, Hibernate Search, whose integration tests don't pass anymore after upgrading to ORM 5.4.0.CR1.

Do you think byte-buddy could get a new release soon, so that we can update our dependencies and have the fix in the next releases?

**Comment by raphw** [comment]
How urgent is this? I can make a quick release tonight but I would ideally fix another minor issue before that I planned to solve early next week.

**Comment by yrodiere** [comment]
@raphw A release next week will do just fine. Thanks!

**Pull request merged**
