### PR TITLE
Fixed failure to generate get methods for fields with capitalized initial letters

### PR DESCRIPTION
**Pull request by haiyanghan**
Fixed failure to generate get methods for fields with capitalized initial letters

### CODE REVIEW

**Comment by haiyanghan** [comment]
@raphw hi, can this pr be merged?

**Comment by raphw** [comment]
I did not have time yet, but was planning to look into this early August. Why did you close this ticket?

**Comment by haiyanghan** [comment]
> 

Sorry, I thought this pr would not be merged

**Comment by raphw** [comment]
I will look into this, but the suggested solution is too simple. Fields can be declared by super types, and the traversal would be duplicated, what I want to avoid. I do not see a trivial solution, though.

**Comment by haiyanghan** [comment]
> I will look into this, but the suggested solution is too simple. Fields can be declared by super types, and the traversal would be duplicated, what I want to avoid. I do not see a trivial solution, though.

I'm not familiar with the source code of bytebuddy, so used a relatively simple wording

**Comment by haiyanghan** [comment]
> I will look into this, but the suggested solution is too simple. Fields can be declared by super types, and the traversal would be duplicated, what I want to avoid. I do not see a trivial solution, though.


I see you have resubmitted this issue, I have closed this PR

**Comment by raphw** [comment]
I have solved it slightly different, but thanks for your suggestion and finding this corner-case.

I am actually not sure if fields with a first capital letter a Java bean compliant, but I think it is worth supporting.

**Pull request closed without merging**
