### PR TITLE
update usage documentation

### PR DESCRIPTION
**Pull request by a364176773**

### CODE REVIEW

**Comment by a364176773** [comment]
@raphw PTAL , I found that the document was a little behind, so I updated it

**Comment by raphw** [comment]
You are right, it is. Thanks for updating. I was still wondering why you needed this additional exception block with the rethrow.

**Comment by a364176773** [comment]
> You are right, it is. Thanks for updating. I was still wondering why you needed this additional exception block with the rethrow.

Thanks for your review. I think that after describing it in this way, the user can clearly know that this exception can be handled extra, rather than thrown out directly

**Comment by raphw** [comment]
Would you remove the changes on the intereptor? Then I can merge this.

**Comment by a364176773** [comment]
> Would you remove the changes on the intereptor? Then I can merge this.

done

**Review by raphw — APPROVED** [review]

**Pull request merged**
