### PR TITLE
Fixes #961 by handing JavaConstant case in FixedValue.value() method

### LINKED ISSUE #961: FixedValue#value(Object) does not consider JavaConstant
I'm aware that `FixedValue` has two `value` methods.  One takes a `JavaConstant` and the other takes an `Object`.

The one that takes an `Object` does not check to see if the `Object` is, itself, a `JavaConstant` implementation.  I think it should, and should then delegate to the `value(JavaConstant)` method.

(Obviously the work around is for the user herself to do the (tedious, boring) `instanceof` check before choosing which method to invoke.)

I'll file a PR soon.

### PR DESCRIPTION
**Pull request by ljnelson**
Signed-off-by: Laird Nelson <ljnelson@gmail.com>

### CODE REVIEW

**Comment by ljnelson** [comment]
Whoops; let me add `TypeDescription` in here too.

**Comment by ljnelson** [comment]
OK; @raphw see what you think

**Comment by raphw** [comment]
I'm not fully understanding the first scenario where the value itself is returned, is this in case you accidentally pass the implementation itself? I'm not sure if I'd like to support this, sounds like an edge case that only happens if there's an error in the code already.

**Comment by ljnelson** [comment]
OK, the thought was just: if you accept an `Object`, then your contract says you accept _anything_.

I'll look at the javadoc.

**Comment by ljnelson** [comment]
Which part of the javadoc did you need fixed?  Do you want me to remove the `@see` tags?

**Comment by raphw** [comment]
Well, `Object` is the most specific common type of all arguments, it's more of a convenience option to intrinsify a choice that a user would otherwise need to take. The contract is in the javadoc which should mention what values are acceptable.

**Comment by ljnelson** [comment]
Sounds like you would prefer if I removed the `if (fixedValue instanceof AssignerConfigurable)` check.  Would that solve the issues?

**Comment by raphw** [comment]
Yes, if you remove it and adjust the javadoc, I'll merge and make a new release.

**Comment by ljnelson** [comment]
OK.  What javadoc adjustments are needed?  All I did was add `@see` tags.  Would you prefer those be removed?

**Comment by ljnelson** [comment]
OK, I've adjusted the javadocs (did not remove the `@see` tags but made it more clear, I hope, about what arguments are acceptable.  I also removed the `AssignerConfigurable` check.  See what you think.

**Comment by ljnelson** [comment]
One hopefully last question.  I just noticed while looking through `MethodCall.ArgumentLoader.ForStackManipulation#of()` that it doesn't deal with `TypeDescription`s.  Should it as well?  And `JavaConstant`?  (I see that it deals with `Class`.)

**Pull request merged**
