### PR TITLE
Break a class initialization deadlock

### PR DESCRIPTION
**Pull request by cushon**
https://github.com/raphw/byte-buddy/issues/1347

### CODE REVIEW

**Comment by raphw** [comment]
I would prefer a fix as suggested in https://github.com/raphw/byte-buddy/commit/5a809653d383454a2f196fc0366b2721c779871c

**Comment by cushon** [comment]
> I would prefer a fix as suggested in [5a80965](https://github.com/raphw/byte-buddy/commit/5a809653d383454a2f196fc0366b2721c779871c)

Okay, thanks, I see that's been committed.

Do you want the test, or should I close the PR?

**Comment by raphw** [comment]
I tried to solve this differently, thanks!

**Comment by cushon** [comment]
> > Do you want the test, or should I close the PR?
>
> I tried to solve this differently, thanks!

Ok, thanks.

It looks like the test did get added in https://github.com/raphw/byte-buddy/commit/50acab840e4d3e241c03f484dcad9b0d0f923dbf.

**Comment by raphw** [comment]
Yes, I'm a bit uncertain if I want to keep it as it's flaky by definition, but until changed my mind to keep it until it's getting in the way at least.

**Pull request closed without merging**
